### ISSUE TITLE
video/rk_vpu_service.h: No such file or directory

### ISSUE THREAD

**Issue by zillevdr** [Miouyouyou/rockchip-vcodec#5]
Hello,
compiling bring:
/usr/src/rockchip-vcodec-testing_dma_interface/vcodec_service.c:45:34: fatal error: video/rk_vpu_service.h: No such file or directory

This header is inside the Rockchip Kernel but not in mainline Kernel. Need I an other patch?

Regards zille

**Comment by Miouyouyou** [comment]
Greetings,

Just a quick review, since I won't able to provide any exhaustive support this week :
- Which branch did you try ?

The only one that "kind of" work with very specific kernel versions is the [retry branch](https://github.com/Miouyouyou/rockchip-vcodec/tree/retry).

Currently, the main branch will just generate memory poisoning, so I highly discourage you to use it at the moment.
That said, IIRC, that header came from the [Rockchip kernel](https://github.com/rockchip-linux/kernel/tree/dev-mpp-device/).
Here : https://github.com/rockchip-linux/kernel/blob/dev-mpp-device/include/uapi/video/rk_vpu_service.h

**Comment by zillevdr** [comment]
Hello Miouyouyou,
I tested with testing_dma_interface and master branch. This evening I will test the retry branch.
Best regards zille

**Comment by zillevdr** [comment]
Hello Miouyouyou,
on kernel.org is no kernel version 4.13. I tried to patch version 4.14.23 but it doesn't work.
Regards zille.

**Comment by Miouyouyou** [comment]
There were a build that barely worked with some specific videos : https://github.com/Miouyouyou/RockMyy-Build/releases/tag/v4.13-VPU-Test

Still, the advance of the VPU driver is stalled due to various reasons I'll provide on my Patreon blog this week. Meanwhile, I don't have much time to concentrate on that.
If you're in a hurry, you might want to see on #linux-rockchip on irc://irc.freenode.net if someone has a better driver currently, for mainline kernels.

**Comment by zillevdr** [comment]
For now I switch back to rockchip-kernel. Many thanks for your support.
Best regards zille
